const monitoramentoData = [
  {
    id: 1,
    processo: 'Ação Trabalhista',
    numero: '0012345-88.2024.5.01.0001',
    tribunal: 'TRT 2ª Região',
    ultimaAtualizacao: 'Hoje, 09:14',
    tipoAtualizacao: 'alert',
    andamentos: 8,
    statusSync: 'intimacao',
    processoId: 1,
  },
  {
    id: 2,
    processo: 'Rescisão Contratual',
    numero: '0021098-33.2024.5.02.0001',
    tribunal: 'TRT 2ª Região',
    ultimaAtualizacao: 'Hoje, 08:30',
    tipoAtualizacao: 'alert',
    andamentos: 5,
    statusSync: 'intimacao',
    processoId: 6,
  },
  {
    id: 3,
    processo: 'Indenização Civil',
    numero: '0033210-11.2023.8.26.0050',
    tribunal: '3ª Vara Cível',
    ultimaAtualizacao: 'Ontem, 16:22',
    tipoAtualizacao: 'ok',
    andamentos: 12,
    statusSync: 'ok',
    processoId: 3,
  },
  {
    id: 4,
    processo: 'Divórcio Consensual',
    numero: '0009871-22.2024.8.26.0100',
    tribunal: '1ª Vara de Família',
    ultimaAtualizacao: 'Ontem, 14:05',
    tipoAtualizacao: 'ok',
    andamentos: 3,
    statusSync: 'ok',
    processoId: 2,
  },
  {
    id: 5,
    processo: 'Usucapião Urbano',
    numero: '0054321-77.2023.8.26.0300',
    tribunal: '1ª Vara Cível',
    ultimaAtualizacao: 'Há 9 dias',
    tipoAtualizacao: 'old',
    andamentos: 2,
    statusSync: 'sem-atualizacao',
    processoId: 5,
  },
  {
    id: 6,
    processo: 'Revisão Contratual',
    numero: '0087654-55.2024.8.26.0200',
    tribunal: '2ª Vara Cível',
    ultimaAtualizacao: 'Hoje, 07:50',
    tipoAtualizacao: 'ok',
    andamentos: 6,
    statusSync: 'ok',
    processoId: 4,
  },
];

const intimacoesData = [
  {
    id: 1,
    titulo: 'Intimação — Ação Trabalhista #0012345',
    sub: 'TRT 2ª Região · Maria Fernanda Costa · Publicado hoje às 09:14',
    tempo: 'Hoje, 09:14',
    lida: false,
    texto: 'Intime-se a parte autora para, no prazo de <strong>15 dias</strong>, manifestar-se sobre os documentos juntados pela reclamada às fls. 142-198, especialmente quanto às folhas de pagamento e registros de ponto apresentados. Sob pena de preclusão.',
    btnPrazo: '+ Adicionar prazo (15 dias)',
    tipo: 'intimacao',
  },
  {
    id: 2,
    titulo: 'Intimação — Rescisão Contratual #0021098',
    sub: 'TRT 2ª Região · Farmácia Bela Saúde · Publicado hoje às 08:30',
    tempo: 'Hoje, 08:30',
    lida: false,
    texto: 'Designa-se audiência de instrução e julgamento para o dia <strong>25/05/2026</strong>, às 14h00, na 2ª Vara do Trabalho. Intime-se as partes e seus advogados. Tragam testemunhas independentemente de intimação.',
    btnPrazo: '+ Adicionar na agenda (25/05)',
    tipo: 'audiencia',
  },
  {
    id: 3,
    titulo: 'Andamento — Indenização Civil #0033210',
    sub: '3ª Vara Cível · Construtora Viva S.A. · Ontem às 16:22',
    tempo: 'Ontem',
    lida: false,
    texto: 'Sentença proferida. Julgou-se procedente em parte o pedido para condenar a ré ao pagamento de R$ 85.000,00 a título de danos materiais. Prazo para recurso de <strong>15 dias</strong> a partir da intimação.',
    btnPrazo: '+ Adicionar prazo recursal',
    tipo: 'sentenca',
  },
  {
    id: 4,
    titulo: 'Intimação — Divórcio Consensual #0009871',
    sub: '1ª Vara de Família · João Renato Alves · 3 dias atrás',
    tempo: '3 dias atrás',
    lida: true,
    texto: 'Processo homologado. Acordo entre as partes registrado em cartório. Arquivamento determinado.',
    btnPrazo: null,
    tipo: 'acordo',
  },
];

// Resultados simulados de busca por OAB
const buscaSimulada = {
  oab: [
    { num: '0012345-88.2024.5.01.0001', tipo: 'Ação Trabalhista — Maria Fernanda Costa', tribunal: 'TRT 2ª Região',   status: 'Urgente',      statusCls: 'pill--urgent',   checked: true  },
    { num: '0098765-44.2023.8.26.0100', tipo: 'Pensão Alimentícia — Lucia Moraes',        tribunal: '2ª Vara Família', status: 'Aguardando',   statusCls: 'pill--waiting',  checked: false },
    { num: '0043219-66.2024.8.26.0050', tipo: 'Dano Moral — Pedro Augusto Neves',         tribunal: '5ª Vara Cível',   status: 'Em andamento', statusCls: 'pill--progress', checked: true  },
    { num: '0011122-33.2024.8.26.0200', tipo: 'Ação de Alimentos — Carla Matos',          tribunal: '3ª Vara Família', status: 'Aguardando',   statusCls: 'pill--waiting',  checked: false },
  ],
  cpf: [
    { num: '0033210-11.2023.8.26.0050', tipo: 'Indenização Civil — Construtora Viva S.A.', tribunal: '3ª Vara Cível', status: 'Em andamento', statusCls: 'pill--progress', checked: true },
    { num: '0076543-10.2022.8.26.0400', tipo: 'Ação de Cobrança — Distribuidora Norte',   tribunal: '4ª Vara Cível', status: 'Em andamento', statusCls: 'pill--progress', checked: false },
  ],
  cnj: [
    { num: '0087654-55.2024.8.26.0200', tipo: 'Revisão Contratual — Ana Paula Rodrigues', tribunal: '2ª Vara Cível', status: 'Em andamento', statusCls: 'pill--progress', checked: true },
  ],
};